# vi: set ft=ruby :

Vagrant::Config.run do |config|

  config.vm.box = "precise"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  #config.vm.share_folder "v-data", "/vagrant_data", "../data"

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "default.pp"
    puppet.module_path = "modules" 
  end

end
